import{a as w,S as E,i as d}from"./assets/vendor-b11e2a50.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const S="44034856-409a23e11e96e3af40ee90684",v="https://pixabay.com/api/";async function q(e,s=1,n=15){try{return(await w.get(v,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:n}})).data}catch(o){throw console.error("Error fetching images:",o),o}}let c;function B(e,s){const n=e.map(({webformatURL:o,largeImageURL:t,tags:r,likes:i,views:p,comments:L,downloads:b})=>`
    <li>
      <a href="${t}">
        <img src="${o}" alt="${r}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${i}</p>
        <p><b>Views</b> ${p}</p>
        <p><b>Comments</b> ${L}</p>
        <p><b>Downloads</b> ${b}</p>
      </div>
    </li>
  `).join("");s.insertAdjacentHTML("beforeend",n),c?c.refresh():c=new E(".gallery a")}function I(e){e.innerHTML=""}function m(){document.querySelector(".load-more").classList.add("hidden")}function M(){document.querySelector(".load-more").classList.remove("hidden")}function O(){document.querySelector(".end-of-results").classList.remove("hidden")}function P(){document.querySelector(".end-of-results").classList.add("hidden")}function $(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const y=document.getElementById("search-form"),A=document.getElementById("search-input"),h=document.getElementById("gallery"),R=document.querySelector(".load-more"),l=document.getElementById("loader");let u="",a=1;y.addEventListener("submit",async e=>{if(e.preventDefault(),u=A.value.trim(),!u){d.warning({title:"Warning",message:"Please enter a search query!"});return}I(h),m(),P(),a=1,await g()});R.addEventListener("click",async()=>{a+=1,await g()});async function g(){f(!0);try{const e=await q(u,a);e.hits.length===0&&a===1?d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(B(e.hits,h),e.totalHits<=a*15?(m(),O()):M(),$())}catch(e){console.error(e),d.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{f(!1),y.reset()}}function f(e){e?(l.classList.remove("hidden"),l.style.display="block"):(l.classList.add("hidden"),l.style.display="none")}
//# sourceMappingURL=commonHelpers.js.map
